theme: jekyll-theme-slate
timezone: America/Los_Angeles
url: https://plaintoast.org
title: Plaintoast
description: Just IT and Security.
author: ZcatK/Plaintoast
locale: en-US
google_analytics: UA-115927520-1
show_downloads: false
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
